name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build OVA
        run:  |
          sudo apt update
          sudo apt -y install debos p7zip qemu-utils zerofree
          cd $GITHUB_WORKSPACE
          chmod +x scripts/tl/*.sh
          chmod +x scripts/*.sh
          chmod +x *.sh
          docker build -t tlvm-builder .
          docker run --rm --interactive --net host--privileged --group-add $(stat -c '%g' /dev/kvm) --volume $(pwd):/recipes -v $(pwd)/images/:/images --workdir /recipes tlvm-builder build.sh

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: "images/*.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
